Consistent behaviour for region, zone, and database_version across modules
terraform-google-modules/terraform-google-sql-db pull request #180
Opened 2021-01-07 01:27 UTC by andreykaipov

Addresses https://github.com/terraform-google-modules/terraform-google-sql-db/issues/179.

As per the comments in each `variables.tf`, this PR makes the following variables required across every SQL module - `region`, `zone`, and `database_version`, addressing the following inconsistencies: 

- `mssql` has a default database version, but `mysql`, `safer_mysql`, and `postgresql` do not.
- `mysql` and `postgresql` do not default the zone, but do default the region.
- `mssql` default both the zone and region.
- `safer_mysql` does not default the zone nor the region.

I don't know how y'all do semver, but this would likely merit a bump to version 5.0.

2021-01-07 18:56 UTC, morgante requested changes
Please don't remove existing defaults. Also check the CONTRIBUTING.md guide to make sure tests pass.

2021-01-07 20:07 UTC, andreykaipov commented
Sorry didn't have a chance to look at the tests last night. In regards to your first suggestion though, removing defaults is actually the intent of the PR. This is done for consistency because in some modules defaults exist, while in others they don't. It's not a big deal, but that behaviour made things awfully confusing for me at first.

2021-01-07 20:08 UTC, andreykaipov commented
Sorry didn't have a chance to look at the tests last night. In regards to your first suggestion though, removing defaults is actually the intent of the PR. This is done for consistency because in some modules defaults exist, while in others they don't. It's not a big deal, but the inconsistent behaviour made things awfully confusing for me at first, and I imagine others too.

2021-01-07 20:12 UTC, morgante commented
You can add defaults to the other modules if you want, but removing defaults is a breaking change.

2021-03-26 19:24 UTC, andreykaipov commented
I'm gonna close this PR since it was my first PR against this repo and I didn't quite follow the contribution guidelines

2021-03-26 19:24 UTC, closed without merging