feat: This adds sample tests based on the new GO test framework
terraform-google-modules/terraform-google-sql-db pull request #239
Opened 2021-08-18 22:12 UTC by g-awmalik

2021-08-18 23:53 UTC, bharathkkb requested changes
Thanks @g-awmalik

2021-08-18 23:53 UTC, bharathkkb commented on Makefile
> +DOCKER_TAG_VERSION_DEVELOPER_TOOLS := 1.0
Lets update readme like https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/965/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L15-R299

2021-08-18 23:53 UTC, bharathkkb commented on test/integration/discover_test.go
> +func TestAll(t *testing.T) { // entry function for the test; can be named as Test*
Where are we invoking the test in CI?
I suggest we add a new build stage for go tests before we phase out the others

2021-08-18 23:53 UTC, bharathkkb commented on test/integration/go.mod
> +module github.com/GoogleCloudPlatform/cloud-foundation-toolkit
nit: 
```suggestion
module github.com/terraform-google-modules/terraform-google-sql-db/test/integration
```

2021-08-18 23:53 UTC, bharathkkb commented on test/integration/mysql-public/mysql_public_test.go
> +	//bpt.TestBlueprint(t, mySqlT,
nit: old code

2021-08-18 23:53 UTC, bharathkkb commented on test/integration/mysql-public/mysql_public_test.go
> +	// import standard formatting and testing packages
nit: I think we can remove this since its from stdlib

2021-08-23 21:02 UTC, g-awmalik commented
Closing this PR based on my discussion with @bharathkkb to isolate the blueprints fixes from the test framework addition.

2021-08-23 21:02 UTC, closed without merging