fix:adds user timeouts as a module variables
terraform-google-modules/terraform-google-sql-db pull request #268
Opened 2021-12-29 21:29 UTC by g-awmalik

This is an interim fix for [this issue](https://github.com/terraform-google-modules/terraform-google-sql-db/issues/264)

2021-12-29 21:33 UTC, morgante requested changes
Please do not use timeouts for this. That's not the right fix.

If there are issues with parallelism, the correct fix is to adjust the `depends_on` so it doesn't start until the earlier resources are done.

We should *never* expose timeout parameters to users.

2021-12-30 04:00 UTC, bharathkkb requested changes
We should do this for [mysql](https://github.com/terraform-google-modules/terraform-google-sql-db/tree/master/modules/mssql) too

2021-12-30 05:03 UTC, g-awmalik commented
@bharathkkb - I can do that as another PR. Let's let this go through to unblock the customer for now.

2022-01-04 18:00 UTC, bharathkkb approved these changes

2022-01-04 18:00 UTC, merged

2022-01-13 10:09 UTC, morgante commented
@g-awmalik Can you add this for mysql and mssql? I want to get those into the release.

2022-01-13 20:23 UTC, g-awmalik commented
@morgante - this includes the change for MySql as well. However, this module doesn't include replica setup for MSSQL yet. I can work on that but we may want to push these changes for now.